// lib/screens/qr_scan_screen.dart
//
// Scans the QR generated by user_main.php → generateQrData().
// QR JSON payload:
//   { "user_id": 8, "full_name": "Mitch Guiwanon Damayo",
//     "email": "mitch@gmail.com", "account_type": "Admin",
//     "password_hash": "$2y$10$..." }
//
// user_id may be int OR string (PHP $_POST gives strings).
// There is NO "access" field in the QR JSON.

import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:mobile_scanner/mobile_scanner.dart';
import '../models/session_model.dart';
import '../utils/app_colors.dart';

class QrScanScreen extends StatefulWidget {
  const QrScanScreen({super.key});

  @override
  State<QrScanScreen> createState() => _QrScanScreenState();
}

class _QrScanScreenState extends State<QrScanScreen>
    with WidgetsBindingObserver {
  final MobileScannerController _ctrl = MobileScannerController(
    detectionSpeed: DetectionSpeed.noDuplicates,
    facing: CameraFacing.back,
    torchEnabled: false,
  );

  bool _processed = false;
  String? _errorMsg;

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) _ctrl.start();
    if (state == AppLifecycleState.paused) _ctrl.stop();
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    _ctrl.dispose();
    super.dispose();
  }

  void _onDetect(BarcodeCapture capture) {
    if (_processed) return;
    final raw = capture.barcodes.firstOrNull?.rawValue;
    if (raw == null || raw.isEmpty) return;

    setState(() => _processed = true);
    _ctrl.stop();

    try {
      final dynamic decoded = jsonDecode(raw);
      if (decoded is! Map) {
        _fail('Not a valid LGU QR code.');
        return;
      }
      final json = Map<String, dynamic>.from(decoded);

      // user_id may arrive as int or string
      final rawId = json['user_id'];
      final userId =
          rawId is int ? rawId : int.tryParse(rawId?.toString() ?? '');

      final fullName = (json['full_name'] as String? ?? '').trim();
      final accountType = (json['account_type'] as String? ?? '').trim();
      final passwordHash = (json['password_hash'] as String? ?? '').trim();
      final email = (json['email'] as String? ?? '').trim();

      if (userId == null || userId == 0) {
        _fail('QR missing user_id.');
        return;
      }
      if (fullName.isEmpty) {
        _fail('QR missing full_name.');
        return;
      }
      if (accountType.isEmpty) {
        _fail('QR missing account_type.');
        return;
      }
      if (passwordHash.isEmpty) {
        _fail('QR missing password_hash.');
        return;
      }

      final session = SessionModel(
        userId: userId,
        firstName: fullName.split(' ').first,
        accountType: accountType,
        access: 'Mobile',
        email: email.isEmpty ? null : email,
        passwordHash: passwordHash,
        fromQr: true,
      );

      if (mounted) Navigator.pop(context, session);
    } catch (e) {
      _fail('Could not read QR: ${e.toString()}');
    }
  }

  void _fail(String msg) {
    if (!mounted) return;
    setState(() {
      _errorMsg = msg;
      _processed = false;
    });
    _ctrl.start();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: AppColors.primary,
        foregroundColor: Colors.white,
        title: const Text('Scan LGU QR Code',
            style: TextStyle(fontWeight: FontWeight.w700)),
        actions: [
          IconButton(
            icon: const Icon(Icons.flashlight_on_rounded),
            onPressed: () => _ctrl.toggleTorch(),
          ),
        ],
      ),
      body: Stack(children: [
        MobileScanner(controller: _ctrl, onDetect: _onDetect),
        _QrOverlay(errorMsg: _errorMsg),
      ]),
    );
  }
}

class _QrOverlay extends StatelessWidget {
  final String? errorMsg;
  const _QrOverlay({this.errorMsg});

  @override
  Widget build(BuildContext context) {
    return Column(children: [
      const Spacer(flex: 2),
      Container(
        margin: const EdgeInsets.symmetric(horizontal: 28),
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
        decoration: BoxDecoration(
          color: Colors.black.withValues(alpha: 0.65),
          borderRadius: BorderRadius.circular(10),
        ),
        child: const Text(
          'Point camera at the QR code\nshown in the admin portal',
          textAlign: TextAlign.center,
          style: TextStyle(color: Colors.white, fontSize: 13, height: 1.5),
        ),
      ),
      const SizedBox(height: 28),
      Container(
        width: 270,
        height: 270,
        decoration: BoxDecoration(
          border: Border.all(color: Colors.white54, width: 2),
          borderRadius: BorderRadius.circular(16),
        ),
        child: Stack(children: _corners(const Color(0xFF3B82F6))),
      ),
      const SizedBox(height: 20),
      AnimatedSwitcher(
        duration: const Duration(milliseconds: 300),
        child: errorMsg != null
            ? Container(
                key: ValueKey(errorMsg),
                margin: const EdgeInsets.symmetric(horizontal: 24),
                padding:
                    const EdgeInsets.symmetric(horizontal: 14, vertical: 11),
                decoration: BoxDecoration(
                  color: AppColors.danger.withValues(alpha: 0.9),
                  borderRadius: BorderRadius.circular(10),
                ),
                child: Row(children: [
                  const Icon(Icons.error_outline,
                      color: Colors.white, size: 18),
                  const SizedBox(width: 8),
                  Expanded(
                      child: Text(errorMsg!,
                          style: const TextStyle(
                              color: Colors.white, fontSize: 13))),
                ]),
              )
            : const SizedBox.shrink(),
      ),
      const Spacer(flex: 3),
      Padding(
        padding: const EdgeInsets.only(bottom: 28),
        child: Text('Ormoc City LGU — Mobile Portal',
            style: TextStyle(
                color: Colors.white.withValues(alpha: 0.4), fontSize: 12)),
      ),
    ]);
  }

  static List<Widget> _corners(Color c) {
    const t = 3.5;
    const l = 30.0;
    return [
      Positioned(
          top: 0, left: 0, child: _C(c: c, t: t, l: l, top: true, lft: true)),
      Positioned(
          top: 0, right: 0, child: _C(c: c, t: t, l: l, top: true, lft: false)),
      Positioned(
          bottom: 0,
          left: 0,
          child: _C(c: c, t: t, l: l, top: false, lft: true)),
      Positioned(
          bottom: 0,
          right: 0,
          child: _C(c: c, t: t, l: l, top: false, lft: false)),
    ];
  }
}

class _C extends StatelessWidget {
  final Color c;
  final double t, l;
  final bool top, lft;
  const _C(
      {required this.c,
      required this.t,
      required this.l,
      required this.top,
      required this.lft});
  @override
  Widget build(BuildContext context) => SizedBox(
      width: l,
      height: l,
      child: CustomPaint(painter: _CP(c: c, t: t, l: l, top: top, lft: lft)));
}

class _CP extends CustomPainter {
  final Color c;
  final double t, l;
  final bool top, lft;
  const _CP(
      {required this.c,
      required this.t,
      required this.l,
      required this.top,
      required this.lft});
  @override
  void paint(Canvas canvas, Size size) {
    final p = Paint()
      ..color = c
      ..strokeWidth = t
      ..style = PaintingStyle.stroke
      ..strokeCap = StrokeCap.square;
    final path = Path();
    if (top && lft) {
      path.moveTo(0, l);
      path.lineTo(0, 0);
      path.lineTo(l, 0);
    } else if (top && !lft) {
      path.moveTo(0, 0);
      path.lineTo(l, 0);
      path.lineTo(l, l);
    } else if (!top && lft) {
      path.moveTo(0, 0);
      path.lineTo(0, l);
      path.lineTo(l, l);
    } else {
      path.moveTo(0, l);
      path.lineTo(l, l);
      path.lineTo(l, 0);
    }
    canvas.drawPath(path, p);
  }

  @override
  bool shouldRepaint(_) => false;
}
